/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      screens: {
        'xs': '475px',
      },
      colors: {
        // Light mode colors
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          50: '#EEF2FF',
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#818CF8',
          500: '#6366F1',
          600: '#4F46E5',
          700: '#4338CA',
          800: '#3730A3',
          900: '#312E81',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        success: '#10B981',
        warning: '#F59E0B',
        error: '#EF4444',
        // AdGrades Brand Colors
        'electric-blue': '#00BFFF',
        'neon-blue': '#008CFF',
        'off-white': '#F4F7FA',
        'charcoal-black': '#0F111A',
        // Silver colors
        silver: {
          DEFAULT: '#C0C0C0',
          50: '#F8F8F8',
          100: '#F0F0F0',
          200: '#E5E5E5',
          300: '#D4D4D4',
          400: '#C0C0C0',
          500: '#A0A0A0',
          600: '#8C8C8C',
          700: '#737373',
          800: '#525252',
          900: '#404040',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out infinite 2s',
        'fade-in': 'fadeIn 1s ease-out',
        'slide-up': 'slideUp 0.8s ease-out',
        'glare': 'glare 0.6s ease-out',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'marquee': 'marquee var(--duration) linear infinite',
        'gradient-drift': 'gradientDrift 15s ease-in-out infinite',
        'gradient-radial': 'gradientDriftRadial 20s ease-in-out infinite',
        'gradient-pulse': 'gradientPulse 4s ease-in-out infinite',
        'silver-glow': 'silverGlow 3s ease-in-out infinite',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'professional-gradient': 'linear-gradient(135deg, #3B82F6 0%, #6366F1 50%, #06B6D4 100%)',
        'subtle-gradient': 'linear-gradient(135deg, hsl(var(--card)) 0%, hsl(var(--muted)) 100%)',
        'gradient-drift': 'linear-gradient(45deg, var(--electric-blue), var(--neon-blue), var(--off-white), var(--charcoal-black))',
        'silver-gradient': 'linear-gradient(135deg, #E5E5E5 0%, #C0C0C0 25%, #FFFFFF 50%, #C0C0C0 75%, #A0A0A0 100%)',
      },
      backdropBlur: {
        xs: '2px',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '92': '23rem',
        '96': '24rem',
        '104': '26rem',
        '112': '28rem',
        '128': '32rem',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      boxShadow: {
        'silver-glow': '0 0 20px rgba(192, 192, 192, 0.4), 0 0 40px rgba(192, 192, 192, 0.3), 0 0 60px rgba(192, 192, 192, 0.2)',
        'silver-glow-intense': '0 0 30px rgba(192, 192, 192, 0.6), 0 0 60px rgba(192, 192, 192, 0.5), 0 0 90px rgba(192, 192, 192, 0.4)',
      },
    },
  },
  plugins: [],
};